dotenv: .env
compiler:
  evm_version: null
  solc:
    version: 0.8.4
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3'
deployer_sepolia: ${PK_SEPOLIA}
account_b: ${PK_B}
account_c: ${PK_C}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
